name: Report Mensal (Gerencial)

on:
  schedule:
    - cron: '0 10 * * 0'
  workflow_dispatch:

jobs:
  send-monthly-report:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      # Ubuntu Fix novamente
      - name: Instalar libs do sistema
        run: |
          sudo apt-get update
          sudo apt-get install -y libasound2t64 libatk-bridge2.0-0 libatk1.0-0 libc6 libcairo2 libcups2 libdbus-1-3 libexpat1 libfontconfig1 libgbm1 libgcc1 libglib2.0-0 libgtk-3-0 libnspr4 libnss3 libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 libxcomposite1 libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 libxtst6 ca-certificates fonts-liberation lsb-release xdg-utils wget

      - name: Instalar Puppeteer
        run: npm install puppeteer

      - name: Rodar Script Mensal
        run: node .github/scripts/monthlyReport.js
        env:
          DASHBOARD_URL: ${{ secrets.DASHBOARD_URL }}
          POWER_AUTOMATE_URL: ${{ secrets.POWER_AUTOMATE_URL }}

      - name: Upload Erro
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: erro-screenshot-monthly
          path: error-screenshot.png
          retention-days: 3